// ── GLSL ES 3.00 Shader: Project 03 - Serene Rotating Water Cube ──────────────
// A serene, slow-motion simulation of a rotating cube of calm water.
// Features water drops hitting the surface, producing expanding ripples, and
// penetrating the translucent water volume with a bullet-time cavitation wake of bubbles.

// ── Structs ──────────────────────────────────────────────────────────────────
struct DropState {
    vec3 pos;       // 3D position of droplet (active in air or inside water)
    float phase;    // 0.0: falling, 1.0: hit & penetrating, 2.0: finished
    float age;      // time since current phase started
    vec2 hitPos;    // where it hit the surface (local XZ coordinates)
    float radius;   // current radius of droplet
    float scale;    // drop scale factor (size, ripple amplitude, and penetration multiplier)
};

// ── Rotation Helpers ─────────────────────────────────────────────────────────
mat3 rotY(float a) {
    float c = cos(a), s = sin(a);
    return mat3(
        c, 0.0, -s,
        0.0, 1.0, 0.0,
        s, 0.0, c
    );
}

mat3 rotX(float a) {
    float c = cos(a), s = sin(a);
    return mat3(
        1.0, 0.0, 0.0,
        0.0, c, -s,
        0.0, s, c
    );
}

vec3 worldToLocal(vec3 p, mat3 m) {
    return m * p;
}

vec3 localToWorld(vec3 p, mat3 m) {
    return transpose(m) * p;
}

// ── Procedural Droplet Simulation ────────────────────────────────────────────
// Simulates 4 independent drops with staggered periodic lifecycles
DropState getDrop(int id, float time) {
    DropState d;
    float fid = float(id);
    
    // Period of the drop cycle (in seconds)
    float period = 3.6;
    float delay = fid * 0.9; // staggered launch times
    
    float tCycle = mod(time - delay, period);
    float cycleId = floor((time - delay) / period);
    
    // Deterministic pseudo-random seed based on drop ID and current cycle
    float seed = fid * 13.54 + cycleId * 57.81;
    
    // Hit position inside the top face bounds [-0.65, 0.65] (avoids edges)
    vec2 randVec = vec2(
        fract(sin(seed * 12.9898) * 43758.5453),
        fract(sin(seed * 78.233) * 43758.5453)
    );
    d.hitPos = (randVec * 2.0 - 1.0) * 0.6;
    
    // Deterministic random scale factor for drop size, ripple size, and depth
    d.scale = mix(0.45, 1.55, fract(sin(seed * 45.19) * 43758.5453));
    
    float fallDuration = 1.0;        // 1 second falling
    float penetrationDuration = 2.0; // 2 seconds penetrating/dissolving
    
    if (tCycle < fallDuration) {
        // Falling Phase
        d.phase = 0.0;
        d.age = tCycle;
        float h = 1.0 - tCycle / fallDuration; // normalized height factor [0, 1]
        // Falls vertically down to y = 1.0
        d.pos = vec3(d.hitPos.x, 1.0 + h * 1.8, d.hitPos.y);
        d.radius = 0.032 * d.scale * (1.0 - h * 0.15); // tear-shaped sizing
    } else if (tCycle < fallDuration + penetrationDuration) {
        // Submerged / Penetration Phase
        d.phase = 1.0;
        d.age = tCycle - fallDuration; // time since impact
        
        // Decelerating penetration depth: depth scale goes up with drop scale
        float maxDepth = 0.45 + 0.45 * d.scale; // larger drops sink deeper
        float depth = maxDepth * (1.0 - exp(-2.5 * d.age));
        d.pos = vec3(d.hitPos.x, 1.0 - depth, d.hitPos.y);
        
        // Droplet gradually dissolves (shrinks) as it joins the water volume
        d.radius = 0.032 * d.scale * exp(-2.0 * d.age);
    } else {
        // Reset / Idle Phase before next cycle
        d.phase = 2.0;
        d.age = tCycle - fallDuration - penetrationDuration;
        d.pos = vec3(0.0, -999.0, 0.0);
        d.radius = 0.0;
    }
    return d;
}

// ── Water Surface Ripples ────────────────────────────────────────────────────
// Sums the concentric wave heights generated by submerged drops
float getRippleHeight(vec2 xz, float time) {
    float height = 0.0;
    for (int i = 0; i < 4; i++) {
        DropState d = getDrop(i, time);
        if (d.phase == 1.0) {
            float dist = length(xz - d.hitPos);
            float age = d.age;
            
            // Concentric wave propagation speed
            float waveSpeed = 0.9;
            float waveFront = age * waveSpeed;
            
            if (dist < waveFront) {
                float distToFront = waveFront - dist;
                
                // Exponential decay over time and distance, scaled by drop intensity
                float amp = 0.022 * d.scale * exp(-1.2 * age) * exp(-1.5 * dist);
                
                // Sine wave shape oscillating behind the expanding wavefront
                float wave = sin(40.0 * distToFront - 18.0 * age) * exp(-4.5 * distToFront);
                
                // Smooth fade-in on impact to prevent popping
                float fadeIn = smoothstep(0.0, 0.12, age);
                
                height += wave * amp * fadeIn;
            }
        }
    }
    return height;
}

// ── Calculate Normal of the Rippled Surface ──────────────────────────────────
vec3 getRippleNormal(vec2 xz, float time) {
    vec2 e = vec2(0.005, 0.0);
    float h = getRippleHeight(xz, time);
    float hX = getRippleHeight(xz + e.xy, time);
    float hZ = getRippleHeight(xz + e.yx, time);
    
    float dhdx = (hX - h) / e.x;
    float dhdz = (hZ - h) / e.x;
    
    // Normal to the heightfield surface y = 1.0 + h(x, z)
    return normalize(vec3(-dhdx, 1.0, -dhdz));
}

// ── Box Signed Distance Function ─────────────────────────────────────────────
float sdBox(vec3 p, vec3 b) {
    vec3 q = abs(p) - b;
    return length(max(q, 0.0)) + min(max(q.x, max(q.y, q.z)), 0.0);
}

// ── Water Cube SDF ───────────────────────────────────────────────────────────
// Displaces the top face of the cube with surface ripples in local space
float sdWaterCube(vec3 p, float time) {
    float dBox = sdBox(p, vec3(1.0));
    
    // Only displace near the top face (y ~ 1.0)
    if (p.y > 0.0 && abs(p.x) < 1.1 && abs(p.z) < 1.1) {
        float rip = getRippleHeight(p.xz, time);
        
        // Attenuate displacement as we move down towards the center
        float weight = smoothstep(0.0, 0.25, p.y);
        
        vec3 perturbedP = p;
        perturbedP.y -= rip * weight;
        
        dBox = sdBox(perturbedP, vec3(1.0));
    }
    return dBox;
}

// ── Distance to Line Segment ─────────────────────────────────────────────────
float sdVerticalSegment(vec3 p, vec2 hitPos, float yStart, float yEnd) {
    vec3 a = vec3(hitPos.x, yStart, hitPos.y);
    vec3 b = vec3(hitPos.x, yEnd, hitPos.y);
    vec3 pa = p - a, ba = b - a;
    float h = clamp(dot(pa, ba) / (dot(ba, ba) + 1e-6), 0.0, 1.0);
    return length(pa - ba * h);
}

// ── Submerged Cavitation Trails SDF ──────────────────────────────────────────
// Renders the bullet-time swirling bubble trails left behind by penetrating drops
float sdTrails(vec3 p, float time) {
    float d = 1e5;
    for (int i = 0; i < 4; i++) {
        DropState ds = getDrop(i, time);
        if (ds.phase == 1.0) {
            // Segment from water surface (1.0) down to current droplet position (ds.pos.y)
            float dSeg = sdVerticalSegment(p, ds.hitPos, 1.0, ds.pos.y);
            
            // Normalize Y location along the trail [0, 1]
            float t = (p.y - ds.pos.y) / (1.0 - ds.pos.y + 1e-6);
            t = clamp(t, 0.0, 1.0);
            
            // Trail radius, wider near the surface impact, tapers towards the droplet, scaled by drop size
            float radius = mix(0.015, 0.038, t) * exp(-0.6 * ds.age) * (0.6 + 0.4 * ds.scale);
            
            // 3D high-frequency procedural noise simulating a stream of bubbles
            float bubbleNoise = sin(p.y * 90.0 - ds.age * 28.0 + float(i) * 17.3) *
                                cos(p.x * 65.0 + float(i) * 11.2) *
                                sin(p.z * 65.0 - float(i) * 8.7);
            
            // Modify distance field to create bumpy bubble structures
            float dTrail = dSeg - (radius + bubbleNoise * 0.015 * exp(-0.35 * ds.age));
            
            // Bound the trail vertically between y = ds.pos.y and y = 1.0
            float dBoxCap = max(dTrail, ds.pos.y - p.y);
            dBoxCap = max(dBoxCap, p.y - 1.0);
            
            d = min(d, dBoxCap);
        }
    }
    return d;
}

// ── External Scene SDF ───────────────────────────────────────────────────────
// Scene representation for external raymarching (water cube + airborne drops)
float sceneSDFExternal(vec3 p, float time) {
    float dCube = sdWaterCube(p, time);
    
    // Only raymarch droplets in the air
    float dDrops = 1e5;
    for (int i = 0; i < 4; i++) {
        DropState ds = getDrop(i, time);
        if (ds.phase == 0.0) {
            float dSphere = length(p - ds.pos) - ds.radius;
            dDrops = min(dDrops, dSphere);
        }
    }
    return min(dCube, dDrops);
}

// ── Internal Scene SDF ───────────────────────────────────────────────────────
// Scene representation for internal refraction raymarching (submerged droplets + wakes)
float sceneSDFInternal(vec3 p, float time) {
    float dDrops = 1e5;
    for (int i = 0; i < 4; i++) {
        DropState ds = getDrop(i, time);
        if (ds.phase == 1.0) {
            float dSphere = length(p - ds.pos) - ds.radius;
            dDrops = min(dDrops, dSphere);
        }
    }
    float dTrails = sdTrails(p, time);
    return min(dDrops, dTrails);
}

// ── Normals ──────────────────────────────────────────────────────────────────
vec3 getExternalNormal(vec3 p, float time) {
    vec2 e = vec2(0.001, 0.0);
    float d = sceneSDFExternal(p, time);
    vec3 n = d - vec3(
        sceneSDFExternal(p - e.xyy, time),
        sceneSDFExternal(p - e.yxy, time),
        sceneSDFExternal(p - e.yyx, time)
    );
    return normalize(n);
}

vec3 getInternalNormal(vec3 p, float time) {
    vec2 e = vec2(0.001, 0.0);
    float d = sceneSDFInternal(p, time);
    vec3 n = d - vec3(
        sceneSDFInternal(p - e.xyy, time),
        sceneSDFInternal(p - e.yxy, time),
        sceneSDFInternal(p - e.yyx, time)
    );
    return normalize(n);
}

vec3 getBoxNormal(vec3 p) {
    vec3 absP = abs(p);
    float maxC = max(absP.x, max(absP.y, absP.z));
    if (maxC == absP.x) return vec3(sign(p.x), 0.0, 0.0);
    if (maxC == absP.y) return vec3(0.0, sign(p.y), 0.0);
    return vec3(0.0, 0.0, sign(p.z));
}

// ── Serene Sky/Background Gradient ───────────────────────────────────────────
vec3 getSereneBackground(vec3 rd) {
    // Soft bright sky gradient: warm horizon to bright sunny blue
    vec3 horizonCol = vec3(0.85, 0.94, 0.90); // warm pale mint/sand
    vec3 midCol     = vec3(0.48, 0.82, 0.88); // soft sky cyan
    vec3 topCol     = vec3(0.20, 0.58, 0.80); // serene blue
    
    float factor = rd.y * 0.5 + 0.5;
    vec3 bg = mix(horizonCol, midCol, smoothstep(0.0, 0.52, factor));
    bg = mix(bg, topCol, smoothstep(0.52, 1.0, factor));
    
    // Sunny glow from upper right
    vec3 lightPos = normalize(vec3(1.2, 1.4, 0.8));
    float dotLight = dot(rd, lightPos);
    
    float glow = pow(max(dotLight * 0.5 + 0.5, 0.0), 8.0);
    bg += vec3(1.0, 0.96, 0.82) * glow * 0.45;
    
    // God rays
    float ray = pow(max(dotLight, 0.0), 20.0) * 0.25;
    ray += pow(max(dotLight, 0.0), 80.0) * 0.45;
    bg += vec3(1.0, 0.98, 0.88) * ray * 0.6;
    
    return bg;
}

// ── Raymarching ──────────────────────────────────────────────────────────────
float raymarchExternal(vec3 ro, vec3 rd, float time) {
    float t = 0.01;
    for (int i = 0; i < 72; i++) {
        vec3 p = ro + rd * t;
        float d = sceneSDFExternal(p, time);
        if (d < 0.001) return t;
        t += d;
        if (t > 8.0) break;
    }
    return -1.0;
}

float raymarchInternal(vec3 ro, vec3 rd, float time, float maxT) {
    float t = 0.01;
    for (int i = 0; i < 48; i++) {
        vec3 p = ro + rd * t;
        float d = sceneSDFInternal(p, time);
        if (d < 0.001) return t;
        t += d;
        if (t > maxT) break;
    }
    return -1.0;
}

// ── Falling Droplet Shading ──────────────────────────────────────────────────
vec3 shadeFallingDroplet(vec3 pLocal, vec3 nLocal, vec3 rdLocal, mat3 mRot) {
    vec3 reflLocal = reflect(rdLocal, nLocal);
    vec3 reflWorld = localToWorld(reflLocal, mRot);
    vec3 reflectColor = getSereneBackground(reflWorld);
    
    // Fresnel reflection
    float fresnel = 0.02 + 0.98 * pow(1.0 - max(dot(-rdLocal, nLocal), 0.0), 5.0);
    
    // Simple diffuse and highlight
    vec3 lightDirLocal = worldToLocal(normalize(vec3(1.2, 1.4, 0.8)), mRot);
    float diff = max(dot(nLocal, lightDirLocal), 0.0);
    float spec = pow(max(dot(reflect(lightDirLocal, nLocal), rdLocal), 0.0), 32.0);
    
    vec3 baseWaterColor = vec3(0.55, 0.88, 0.78);
    vec3 col = mix(baseWaterColor * (diff * 0.55 + 0.35), reflectColor, fresnel);
    col += vec3(1.0, 0.98, 0.92) * spec * 1.1; // bright sunny highlight
    
    return col;
}

// ── Main Image Shader ────────────────────────────────────────────────────────
void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    // 1. Coordinates and Aspect Ratio Setup
    vec2 uv = fragCoord / iResolution.xy;
    vec2 pScreen = (uv - 0.5) * 2.0;
    pScreen.x *= iResolution.x / iResolution.y;
    
    // 2. Camera Setup (World Space)
    float camRadius = 4.0;
    float camSpeed = 0.12;
    vec3 ro = vec3(
        camRadius * sin(iTime * camSpeed),
        1.1 + 0.25 * sin(iTime * camSpeed * 2.2), // gentle vertical drift
        camRadius * cos(iTime * camSpeed)
    );
    vec3 lookAt = vec3(0.0, 0.1, 0.0);
    
    // View transform matrix
    vec3 w = normalize(lookAt - ro);
    vec3 u = normalize(cross(w, vec3(0.0, 1.0, 0.0)));
    vec3 v = cross(u, w);
    
    // View ray direction
    vec3 rd = normalize(pScreen.x * u + pScreen.y * v + 1.6 * w);
    
    // 3. Define Cube Rotation Matrix
    mat3 mRot = rotX(iTime * 0.08) * rotY(iTime * 0.13); // slow relaxing rotation
    
    // Transform ray to the rotating local space of the cube
    vec3 roLocal = worldToLocal(ro, mRot);
    vec3 rdLocal = worldToLocal(rd, mRot);
    
    // 4. Raymarch External Scene
    float tHit = raymarchExternal(roLocal, rdLocal, iTime);
    
    vec3 color = vec3(0.0);
    
    if (tHit < 0.0) {
        // Ray missed the scene; draw background
        color = getSereneBackground(rd);
    } else {
        vec3 pLocal = roLocal + rdLocal * tHit;
        vec3 nLocal = getExternalNormal(pLocal, iTime);
        
        // Determine whether we hit an airborne droplet or the water cube
        float dCube = sdWaterCube(pLocal, iTime);
        
        // Small check: if closer to droplets, shade as droplet
        bool hitDroplet = false;
        for (int i = 0; i < 4; i++) {
            DropState ds = getDrop(i, iTime);
            if (ds.phase == 0.0) {
                float dSphere = length(pLocal - ds.pos) - ds.radius;
                if (abs(dSphere - dCube) < 0.002 || dSphere < dCube) {
                    hitDroplet = true;
                    break;
                }
            }
        }
        
        if (hitDroplet) {
            color = shadeFallingDroplet(pLocal, nLocal, rdLocal, mRot);
        } else {
            // ── Refraction and Transmission inside the Water Cube ────────────
            
            // Fresnel coefficient
            float cosTheta = max(dot(-rdLocal, nLocal), 0.0);
            float fresnel = 0.02 + 0.98 * pow(1.0 - cosTheta, 5.0);
            
            // Reflection
            vec3 reflLocal = reflect(rdLocal, nLocal);
            vec3 reflWorld = localToWorld(reflLocal, mRot);
            vec3 reflectColor = getSereneBackground(reflWorld);
            
            // Refraction direction (air 1.0 to water 1.333)
            vec3 refrLocal = refract(rdLocal, nLocal, 1.0 / 1.333);
            
            // Analytical Ray-Box intersection to find the exit distance
            vec3 safeRefr = sign(refrLocal) * max(abs(refrLocal), 1e-6);
            vec3 tMin = (vec3(-1.0) - pLocal) / safeRefr;
            vec3 tMax = (vec3(1.0) - pLocal) / safeRefr;
            vec3 t2 = max(tMin, tMax);
            float tExit = min(min(t2.x, t2.y), t2.z);
            
            // Raymarch the internal medium of the box along the refracted ray
            float tHitInternal = raymarchInternal(pLocal + refrLocal * 0.005, refrLocal, iTime, tExit);
            
            vec3 waterColor = vec3(0.0);
            
            // Beer-Lambert absorption: translucent greens and blues
            // Red absorbed moderately, green very little, blue slightly
            vec3 absorptionCoeff = vec3(0.35, 0.04, 0.12) * 0.8;
            
            // Volumetric ambient scatter color (makes the water body glow teal/cyan from inside)
            vec3 scatterColor = vec3(0.08, 0.26, 0.22);
            
            if (tHitInternal > 0.0) {
                // Ray hit an internal bubble/droplet or cavitation wake
                vec3 pInternal = pLocal + refrLocal * (0.005 + tHitInternal);
                vec3 nInternal = getInternalNormal(pInternal, iTime);
                
                // Determine whether we hit a droplet or trail
                float dDrop = 1e5;
                for (int i = 0; i < 4; i++) {
                    DropState ds = getDrop(i, iTime);
                    if (ds.phase == 1.0) {
                        float d = length(pInternal - ds.pos) - ds.radius;
                        dDrop = min(dDrop, d);
                    }
                }
                float dTrail = sdTrails(pInternal, iTime);
                
                // Common lighting vectors
                vec3 lightDirLocal = worldToLocal(normalize(vec3(1.2, 1.4, 0.8)), mRot);
                float diff = max(dot(nInternal, lightDirLocal), 0.0);
                float spec = pow(max(dot(reflect(lightDirLocal, nInternal), refrLocal), 0.0), 16.0);
                float rim = pow(1.0 - max(dot(-refrLocal, nInternal), 0.0), 4.0);
                
                vec3 itemColor = vec3(0.0);
                if (dDrop < dTrail + 0.002) {
                    // Submerged droplet: glowing silver/cyan air bubble catching sunlight
                    itemColor = vec3(0.85, 0.98, 0.95) * (diff * 0.5 + 0.35) + vec3(1.0, 0.98, 0.92) * spec * 1.15;
                    itemColor += vec3(0.1, 0.9, 0.75) * rim * 1.8;
                } else {
                    // Cavitation trail: turbulent bright white/gold/cyan micro-bubbles
                    float foamNoise = fract(sin(dot(pInternal.xyz, vec3(12.9898,78.233,45.164))) * 43758.5453);
                    vec3 foamCol = mix(vec3(0.95, 1.0, 0.98), vec3(0.4, 0.95, 0.85), foamNoise);
                    itemColor = foamCol * (diff * 0.55 + 0.45) + vec3(1.0, 0.98, 0.92) * spec * 0.8;
                    itemColor += vec3(0.1, 0.85, 0.72) * rim * 1.5;
                }
                
                // Attenuate internal bubble color by absorption from entry to hit point
                waterColor = itemColor * exp(-absorptionCoeff * tHitInternal);
                
                // Add volumetric light scattering
                waterColor += scatterColor * (vec3(1.0) - exp(-absorptionCoeff * tHitInternal)) * 0.5;
            } else {
                // Ray exits the box back into the air
                vec3 pExit = pLocal + refrLocal * tExit;
                vec3 nExit = getBoxNormal(pExit);
                
                // If exiting the top face, use the wavy ripple normal instead of flat box normal
                if (pExit.y > 0.99) {
                    nExit = getRippleNormal(pExit.xz, iTime);
                }
                
                // Refract exit ray (water 1.333 to air 1.0)
                vec3 refrExitLocal = refract(refrLocal, -nExit, 1.333 / 1.0);
                if (length(refrExitLocal) < 0.01) {
                    // Total Internal Reflection inside the cube
                    refrExitLocal = reflect(refrLocal, -nExit);
                }
                
                vec3 refrExitWorld = localToWorld(refrExitLocal, mRot);
                vec3 exitColor = getSereneBackground(refrExitWorld);
                
                // Attenuate background light through the entire cube width
                waterColor = exitColor * exp(-absorptionCoeff * tExit);
                
                // Add volumetric light scattering
                waterColor += scatterColor * (vec3(1.0) - exp(-absorptionCoeff * tExit)) * 0.5;
            }
            
            // Mix refraction with external surface reflection
            color = mix(waterColor, reflectColor, fresnel);
            
            // Glistening warm sun highlights on the cube surface
            vec3 lightDirLocal = worldToLocal(normalize(vec3(1.2, 1.4, 0.8)), mRot);
            float surfaceSpec = pow(max(dot(reflect(lightDirLocal, nLocal), rdLocal), 0.0), 64.0);
            color += vec3(1.0, 0.98, 0.92) * surfaceSpec * fresnel * 2.0;
        }
    }
    
    // 5. Calm Vignette and Post Processing
    float vignette = uv.x * uv.y * (1.0 - uv.x) * (1.0 - uv.y);
    vignette = clamp(pow(16.0 * vignette, 0.2), 0.0, 1.0);
    color *= vignette;
    
    // Sub-pixel noise to prevent banding in dark gradients
    float dither = fract(sin(dot(fragCoord.xy, vec2(12.9898, 78.233))) * 43758.5453);
    color += vec3(dither - 0.5) / 255.0;
    
    fragColor = vec4(color, 1.0);
}
